GET http://localhost:3000/messages

###

GET http://localhost:3000/messages/62562ba7502c80020adb060e

###

POST http://localhost:3000/messages
Content-Type: application/json

{
    "message" : "hey guys, whats up?",
    "author" : "mms student 1"
}

###

DELETE http://localhost:3000/messages/62563441502c80020adb0610